name: Export de métricas

on:
  pull_request:
    branches: [main, develop]
    types: [closed]

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Msgram Helper Action
        uses: fga-eps-mds/2023-1-MeasureSoftGram-Helper-Action@v0.1.6-alpha
        id: msgram
        with:
          githubToken: ${{ secrets.API_TOKEN_DOC }}
          metricsRepo: "2023-1-MeasureSoftGram-doc"